### ISSUE TITLE
Add projects to clotributor

### ISSUE THREAD

**Issue by nate-double-u** [cncf/clotributor#154]
How do we add projects to clotributor?

I've added a 'help wanted' label to Vitess' https://github.com/vitessio/website/issues/1169 issue, and it is open and unassigned, but I can't find it in the [clotributor search](https://clotributor.dev/search?ts_query_web=vitess&page=1).

Am I missing something? Do projects need to be added to a list to be crawled?

**Comment by tegioz** [comment]
Hi @nate-double-u 👋🏻

At the moment it feeds from CLOMonitor's data files (https://github.com/cncf/clotributor#projects-and-repositories).

Maybe that repository hasn't been added to CLOMonitor yet.

**Comment by nate-double-u** [comment]
Interesting, looks like it's there
https://clomonitor.io/projects/cncf/vitess

**Comment by nate-double-u** [comment]
Oh, i see, maybe the docs site repo hasn't been added. Will check that shortly 🙂

**Comment by nate-double-u** [comment]
Would the additions I made in https://github.com/cncf/clomonitor/pull/888 be enough for clotributor to register the vitess website? Or is there a check-set i'm missing?

**Comment by tegioz** [comment]
Yes, I think the `docs` check-set is a great fit for that repo 👍

**Comment by tegioz** [comment]
The Vitess issue you referenced is already listed on CLOTributor 🙂 Thanks!
