### ISSUE TITLE
Be able to filter by difficulty

### ISSUE THREAD

**Issue by caniszczyk** [cncf/clotributor#49]
It would be nice to filter by difficulty of issue

maybe we can have a label standard like "level" or "complexity"

"level/1"
"level/2"
"level/3"
"level/4"
"level/5"

Where 1 is easy and 5 is difficult

**Comment by tegioz** [comment]
Yes, that would be great. As soon as projects start using those labels on issues we can add this new filter. Another option could be to use something like `easy`, `medium` or `hard` as @cathyhongzhang suggested in #55.

Maybe once the labels we'll recommend for this feature are defined, we can document them in the README file explaining that we'll soon add a filter for this and that it'd be very helpful if projects could start using those labels in issues with the `help wanted` label.

**Comment by tegioz** [comment]
This is ready! 🙂 You can find the labels we are using at the moment [here](https://github.com/cncf/clotributor#labels-with-special-meaning). If you'd like to add more or replace them please let us know.

<img width="1502" alt="difficulty" src="https://user-images.githubusercontent.com/1213902/205377753-e1f97c5a-84ae-46c4-83fc-9fc146ce7820.png">
