### ISSUE TITLE
Be able to filter by issues that have a "willing to mentor"

### ISSUE THREAD

**Issue by caniszczyk** [cncf/clotributor#50]
Essentially we should be able to filter and surface issues from community members who are willing to put in EXTRA mentoring time. This should be some type of label "mentoravailable"

**Comment by tegioz** [comment]
Done! You can find the labels we are using at the moment [here](https://github.com/cncf/clotributor#labels-with-special-meaning). If you'd like to add more or replace it please let us know 🙂 

<img width="1502" alt="mentor_available_1" src="https://user-images.githubusercontent.com/1213902/205378025-49a78f37-b3af-4d9a-896f-bc3bf87551f7.png">

The next screenshot is not real as no issue is using yet the `mentor available` label. It was just to illustrate how it would look like.

<img width="1343" alt="mentor_available_2" src="https://user-images.githubusercontent.com/1213902/205378034-7cdb8f09-455e-466a-8bcb-c13933eb0be0.png">
