### ISSUE TITLE
Be able to filter by project

### ISSUE THREAD

**Issue by caniszczyk** [cncf/clotributor#51]
right now, if I type "meshery" or "istio" in the search box, I get a mix of issues

Ideally I'd like to have a search query like "project: istio" and it only have things from the istio org

**Comment by tegioz** [comment]
I see what you mean. When projects are closely related and labels/topics overlap, it can be tricky.

We've just added a projects filter in the UI for exact matches for now 🙂

<img width="1449" alt="Screenshot 2022-12-02 at 18 48 51" src="https://user-images.githubusercontent.com/1213902/205354525-ae9dc52e-696d-4675-b840-6c1054ad97b6.png">
