### ISSUE TITLE
Feature request: Badge for GH repo README

### ISSUE THREAD

**Issue by jmertic** [cncf/clotributor#568]
It would be great to have a badge one could put in their README file that lists the number of issues listed for the project on CLOtributor.

**Comment by 8rxn** [comment]
If this is something that'll take shape, I'd love to work on it. 
I made some badges recently as well.

**Comment by jmertic** [comment]
@8rxn  I'll defer to @tegioz on the timing of this - but appreciate your interest in this feature!

**Comment by tegioz** [comment]
Hi @jmertic!

CLOTributor's main goal is to surface interesting GitHub issues to work on. If a potential contributor is already in GitHub in the context of a specific project/repo, IMHO it'd be better to just include a badge displaying the number of issues that match some filters relevant to the project (good first issues, help wanted, etc) that would take the user to the issues section of that repo (applying those filters).

Sending them to CLOTributor to find issues links that would point them back to GitHub may be a bit confusing, specially considering that in GitHub they may find additional information (i.e. comments on issues, PRs linked to open issues not assigned yet, etc) and extra issues filters not available in CLOTributor.

**Comment by jmertic** [comment]
Hey @tegioz, that's probably fair. I thought it would drive more awareness of CLOTributor and a project's involvement, but for actual discovery, it's an extra step.

That all said - the issue discovery experience is much better in CLOtributor vs GitHub Issues. So I could see value in such a badge being used.
