### ISSUE TITLE
kubestellar/kubestellar (sandbox project) is not listed

### ISSUE THREAD

**Issue by clubanderson** [cncf/clotributor#639]
Hello @tegioz I just checked again with clotributor re: listing KubeStellar's issues. We have issues opened since March 2024 with the 'help wanted' tag and they are not showing up on your site. Can you look into this?

**Comment by tegioz** [comment]
Hi @clubanderson 👋 

CLOTributor only surfaces open issues with the `help wanted` label that are **unassigned**. I've taken a quick look at the kubestellar repo and it looks like all issues labelled with help wanted already have an assignee.

Hope this helps 🙂
