### ISSUE TITLE
Filter quickly for issues involving docs

### ISSUE THREAD

**Issue by caniszczyk** [cncf/clotributor#95]
We should find a way to easily filter issues for docs related projects + issues.

I guess this can just be a "docs" issue label but maybe there's something more clever we can do

**Comment by tegioz** [comment]
Hi @caniszczyk

We've added a new `area` filter to handle this. We could include more areas like backend, frontend, etc. At the moment an issue is included in the docs area if we can find a label that contains the `docs` or `documentation` strings. It'd be great if we could let projects know about the labels with special meaning for CLOTributor (we've documented them a bit in the README file).

<img width="1513" alt="area-filter" src="https://user-images.githubusercontent.com/1213902/210223839-91cc3ac2-422f-4ddf-802a-90237c8163bb.png">
